### PR TITLE
Add me as an author

### PR DESCRIPTION
**Pull request by minterior**
:relaxed:

### CODE REVIEW

**Comment by minterior** [comment]
I have no more PR pending. Let's release! :sunglasses: :metal:

**Comment by minterior** [comment]
@zanderbaldwin I think the new release version should have been `3.0.0` because you removed the method `validate`, breaking backwards compatibility.

**Comment by zanderbaldwin** [comment]
Dammit I forgot about that... Well I know it's really bad but I'll remove the `2.1.0` tag tomorrow... It's not like many people are using it yet :smile:

**Comment by minterior** [comment]
Hehe, true, but it's fine for me as well; in fact it's better to remove it to not cause problems to actual [thousand] users :laughing:

**Pull request merged**
