### PR TITLE
Add methods `isVersion4` and `isVersion6` and let child classes to be instantiated

### PR DESCRIPTION
**Pull request by minterior**
Unit tests added to keep 100% code coverage.

### CODE REVIEW

**Comment by zanderbaldwin** [comment]
Hi! Thanks for the pull request - I didn't get a notification from GitHub so I've only just noticed it, sorry about that! I'll look over it in the next few hours (I'm at work at the moment) :smile:

**Comment by zanderbaldwin** [comment]
There are some good ideas here, and would love to merge them in - but not all of them (such as line lengths which is not enforceable according to PSR-2).

Would you mind me rearranging your pull request into separate feature-commits (you'll still be the author of the commits and I'll show you the temporary branch before merging it in), or would you like to amend them yourself?

**Comment by minterior** [comment]
Thank you :) Which ones (or commits) do you want out of the PR?

Last commit `b27b13c` fixes issue https://github.com/darsyn/ip/issues/4

**Comment by zanderbaldwin** [comment]
#### Keep
- The `isVersion4()` and `isVersion6()` methods are a good idea. Keep them.
- Adding late static bindings is a good idea, but, just use `new static` directly instead of adding `createIp()`. Adding another method that replicates the constructor doesn't really improve anything.
- Spelling mistake changes. I hope eventually that I can specify PHP7 as a minimum version in a future major release and there would be no need to have phpdoc-comments since everything will be enforced in the method declarations, hurray for type and return hints!
- Definitely, absolutely, keep the `getIpLength()` bug-fix method!

#### Don't Keep
- Line length changes. PSR-2 specifies that there is no hard-limit on line length, and keeping them within 80 characters is just a suggestion (from the old days where terminals were only 80 characters wide).
- Don't bother with the `isBinaryNotation()` static method - it works fine, but I plan on removing the `validate()` static method because having static methods kinda defeat the point of a value-object. The validation occurs automatically when instantiating a new instance of the object.

#### Version

Calculating the version only once is good, but it's not always necessary to calculate it at all - I'm not quite sure what to do for this. Any thoughts?

**Comment by minterior** [comment]
- Method `createIp` avoids code duplication, so you don't repeat the construction of the class, done twice. But if you don't want it, it's ok.
- Regarding line length, you're right PSR-2 says no hard limit, but it definitely recommends to keep your lines less than 80 chars. And that's not for the old terminals, it's a cognitive limitation of humans and to easy two or three ways code comparisons. You can read more here:
    - http://paul-m-jones.com/archives/276
    - https://news.ycombinator.com/item?id=5436993
    - https://www.reddit.com/r/ruby/comments/3eu83n/how_important_is_the_80_character_limit_in_2015/
    - https://books.google.es/books?id=Zx7MsVG0DC0C&printsec=frontcover

    That said, I can remove line length changes, although there are big advantages with 80.
- +1 To remove the `validate()` static method :+1: I didn't want statics over there :P
- Version: another option here is to do not calculate the version in the constructor and just do it on demand and only the first time, storing the version in a class attribute for next times.

**Comment by zanderbaldwin** [comment]
- I'm not sure that `callingMethod()` &rarr; `createIp()` &rarr; `__construct()` avoids duplication any more than `callingMethod()` &rarr; `__construct()`, nor do I understand how object construction is repeated? Value-objects don't really have any need for factory methods.
- Those links were quite interesting to read, so yeah you've convinced me. But since the coding style has nothing to do with the current pull request, would you mind creating another with those changes?
- The `validate()` method has been removed in #5, rebase/pull those changes in - that change will cause conflicts with your pull request though, sorry!
- Lazy processing is probably the best bet for calculating the version. I personally would combine the `getVersion()` and `findVersion()` methods, something along the lines of:

```php
public function getVersion()
{
    if ($this->version !== null) {
        return $this->version;
    }
    $ip = preg_replace('/^\0{12}/', '', $this->getBinary());
    return $this->version = self::getIpLength($ip) < 16
        ? static::VERSION_4
        : static::VERSION_6;
}
```

There should be no need to check exact lengths, or throw an exception, because the immutable value was validated on object instantiation. Most things are private so the class can only be extended, not modified.

**Comment by minterior** [comment]
Excellent! I will rebase and create another separate PR :+1: 

I'm at work now, so wait patiently please :smile:

**Comment by zanderbaldwin** [comment]
That's fine! Take as much time as you need, I'm not exactly the quickest at replying either! :smile:

**Pull request closed without merging**
